[package]
name = "mc_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.1"
rand_chacha = "0.9.0-alpha.1"

[profile.dev]
opt-level = 3
overflow-checks = false
